app = "swap-it-socket"
primary_region = "ams"

[build]
  dockerfile = "socket.dockerfile"

[processes]
  app = "npm run socket"

[[mounts]]
  source = "data"
  destination = "/app/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "10GB"

[[services]]
  internal_port = 3001
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
